title: Custom Docker Image for Java-based Applications
description: An open-source project that provides a Docker image designed for running Java-based applications
show_downloads: false
theme: jekyll-theme-cayman
