version: '3'
services:
  java:
    container_name: java
    image: 'api.repoflow.io/desiderati/docker/java:21'
    ports:
      # Descomentar a linha abaixo para adicionar suporte à depuração remota.
      - '8090:8090'

      # Descomentar a linha abaixo para adicionar suporte ao Agente JMX.
      #- 9010:9010

    environment:
      # Executar id -u ${USER}, de modo a descobrir o Id do usuário local.
      # Os arquivos gerados nos volumes mapeados, terão as permissões do usuário local.
      - LOCAL_USER_ID=1000

      # Descomentar a linha abaixo para adicionar suporte à depuração remota.
      - ENABLE_DEBUG=true

      # Descomentar a linha abaixo para adicionar suporte ao Agente JMX.
      #- ENABLE_JMX=true

      # Variáveis do sistema.
      - LOG_FILE=/opt/java-app/logs/java.log
      - JAVA_XMX=512m
      - JAVA_CPUS=1
      - TZ=America/Sao_Paulo

    volumes:
      - ./tmp/:/tmp/
      - ./config/:/opt/java-app/config/
      - ./logs/:/opt/java-app/logs/

      # Define a aplicação a ser executada. Descomentar a linha abaixo.
      #- ./modules/java-exec.jar:/opt/java-app/app.jar
